import Head from 'next/head';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div className='bg-[#d4d4d4] dark:bg-black dark:text-white h-screen overflow-y-scroll md:space-y-6'>

      <Head>
        <title>Feed | Upcolor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://weblike-upcolor.ssl-lolipop.jp/UpColor/includes/images/Up.png" />

      </Head>
      <Header/>

      <main className='flex justify-center gap-x-5 px-4 sm:px-12'>
        <div className='flex flex-col md:flex-row gap-5'>
          <Sidebar/>
          {/* {SideBar} */}
          {/* {Feed} */}
        </div>
          {/* {Widgets} */}
      </main>
    </div>
  )
}
