import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Modal from "../components/Modal";
import { useRecoilState } from "recoil";
import { modalState, modalTypeState } from "../atoms/modalAtom";
import { AnimatePresence } from 'framer-motion';

export default function Home({ posts, articles }) {
  const [modalOpen, setModalOpen] = useRecoilState(modalState);
  const [modalType, setModalType] = useRecoilState(modalTypeState);
  const router = useRouter();
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      // The user is not authenticated, handle it here.
      router.push("/home");
    },
  });

  return (
    <div className='bg-[#d4d4d4] dark:bg-black dark:text-white h-screen overflow-y-scroll md:space-y-6'>

      <Head>
        <title>Feed | Upcolor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://weblike-upcolor.ssl-lolipop.jp/UpColor/includes/images/Up.png" />

      </Head>
      <Header/>

      <main className='flex justify-center gap-x-5 px-4 sm:px-12'>
        <div className='flex flex-col md:flex-row gap-5'>
          <Sidebar/>
          {/* {SideBar} */}
          {/* {Feed} */}
          <Feed/>
        </div>
          {/* {Widgets} */}
          <AnimatePresence>
          {modalOpen && (
            <Modal handleClose={() => setModalOpen(false)} type={modalType} />
          )}
        </AnimatePresence>
      </main>
    </div>
  )
}
export async function getServerSideProps(context) {
  // Check if the user is authenticated on the server....
  const session = await getSession(context)
  if (!session) {
    return {
      redirect: {
        permanent : false,
        destination : "/home",
      },
    };
  }
  return {
    props : {
      session,
    },
  };

}
